language: cpp
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libboost1.54-dev yasm zlib1g-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost yasm; fi
script:
  - make
dist: trusty
cache:
  directories:
  - .downloads