language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost1.54-dev yasm zlib1g-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm || brew upgrade yasm || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc || brew upgrade gcc || true; brew link --overwrite gcc ; fi
script:
  - compgen -c gcc ; make
dist: trusty
cache:
  directories:
  - .downloads
matrix:
  allow_failures:
    - osx
