language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost1.54-dev yasm zlib1g-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
script:
  - for D in $(echo $PATH | tr : \\n); do ls $D/gcc-* ; done ; make
dist: trusty
cache:
  directories:
  - .downloads
