language: cpp
script: sudo add-apt-repository -y ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get install libboost1.54-dev ffmpeg yasm zlib1g-dev && make
dist: trusty
sudo: required
cache:
  directories:
  - .downloads
  - libraries
